#!/usr/bin/env bash

if [[ -n "$SESSION_NAME" ]]; then
    # Instantly kill the user's interactive subshell.
    # This automatically drops control back to manage/start, which executes the log cleanup!
    kill -9 $PPID
else
    echo "[Global] You are already in global mode."
fi